### ISSUE TITLE
Sat status misleading

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enroute#110]
Sat status is being displayed "ok" as soon as the receiver is turned on (but has not yet got enough data to deliver valid position data). Therefore the Sat reveiver should differentiate and display three states: 
e.g.
- off
- searching
- valid data (often: "3D FIX" )

**Comment by kebekus** [comment]
Hmmm … I was not able to reproduce the issue. Can you re-comfirm the problem, and perhaps attach a screencast video/screenshot or similar, so I can see how things look on your device? -- Thanks!

**Comment by kebekus** [comment]
Closed because problem does not occur anymore.
