### ISSUE TITLE
Easier possibility to  move content (e.g. charts, routes) to SD cart

### ISSUE THREAD

**Issue by spuckebaer** [Akaflieg-Freiburg/enroute#115]
When trying to move content to SD charts with standard android means it failes. (No chart displayed when open enroutes)

Even if I know charts in enroute are extremly small I would love to have a solution in enroute (move charts to SD)

**Comment by kebekus** [comment]
Thanks for your suggestion. After some consideration, I have however decided to not pursue the issue. Moving database files while they are in use invites all kinds of disaster, and it would be quite an effort to implement the necessary safeguards. I regret that I have no better news and ask for your understanding that our resources are limited and that we need to prioritise our efforts.
