### ISSUE TITLE
Night Modus

### ISSUE THREAD

**Issue by propellertje** [Akaflieg-Freiburg/enroute#117]
Eyes are rather sensitive to light especially in a dark environment such as Night Flying.

Screen devices are rather bright and sometimes it is not sufficient to reduce the brightness of a device for Night Flying.

Request is to implement a night modus. Kind of a Dark Modus.
See the screen of the commercial product Foreflight.

Keep up the good work! Kind regards Bernard

**Comment by kebekus** [comment]
Thank you for your suggestion. I am considering this seriously, but I cannot promise anything at this stage. Perhaps you could attach a screenshot of foreflight? -- Thanks.

**Comment by propellertje** [comment]
https://foreflight-www.s3.amazonaws.com/assets/weather_double_chrome_www.png

Dear sir, Sorry for my late answer. Hope this helps. Kind regards Bernard

**Comment by kebekus** [comment]
Thanks for the image. I will look at this, but please give me a little time.

**Comment by propellertje** [comment]
You welcome, no hurry and thanks a lot for your effort!

Op vr 25 dec. 2020 om 07:03 schreef Stefan Kebekus <notifications@github.com

**Comment by kebekus** [comment]
Done. The feature will appear in v2.3.0, which is scheduled to appear in mid-February. Thanks again for the suggestion!

**Comment by propellertje** [comment]
Thank you so much! Really appreciate your effort. Kind regards, Bernard

Op vr 22 jan. 2021 om 08:03 schreef Stefan Kebekus <notifications@github.com
