### ISSUE TITLE
can not save flight routes

### ISSUE THREAD

**Issue by zehess** [Akaflieg-Freiburg/enroute#124]
Error Message: 
"unable to open the file 'storage/emulated/0/enroute flight navigation/flight routes/...' geojson for writing"
Android 10
moto g(7) plus

**Comment by kebekus** [comment]
Thank you for your report. So far, I was unable to reproduce the issue. Can you please provide me with more information (what file name did you choose?). Perhaps you can also attach a few screenshots or a screencast video that shows the issue?

Best,

Stefan.

**Comment by zehess** [comment]
Hi Stefan,

danke für die rasche Nachfrage!
Es geht bei mir um das erstmalige Speichern einer Route über
"Flugstrecke"-"in Bibliothek speichern", Speichername wie vorgeschlagen
(funktioniert aber auch mit eigenem einfacheren Namen nicht). Screenshots
anbei.

Der In der Fehlermeldung erwähnte Dateipfad ist vorhanden und beschreibbar.

Vielen Dank für die Mühe
Carsten Schneider

Stefan Kebekus <notifications@github.com> schrieb am Mo., 28. Dez. 2020,
13:23:

**Comment by kebekus** [comment]
I am able to reproduce the issue now. Currently working on a fix.

**Comment by kebekus** [comment]
Hallo,

ich glaube, dass ich das Problem gelöst habe. Kannst Du bitte die aktuelle Beta-Version (=2.2.0) der App installieren und bestätigen, dass das Problem nicht mehr auftritt? Um die Beta-Version zu bekommen, musst Du dich über den folgenden Links als Beta-Tester anmelden:

    https://play.google.com/apps/testing/de.akaflieg_freiburg.enroute

Alternativ kannst Du Dich in "Google Play" als Beta-Tester anmelden. Du kannst das Beta-Programm natürlich jederzeit wieder verlassen und zur stabilen Version der App zurückkehren.

Grüße,

Stefan.

**Comment by zehess** [comment]
Hallo,

ja, Flugstrecken speichern, laden und umbenennen funktioniert jetzt
tadellos.

Vielen Dank und ein schönes 2021

C. Schneider

Stefan Kebekus <notifications@github.com> schrieb am Mi., 30. Dez. 2020,
08:32:

**Comment by kebekus** [comment]
Wunderbar, danke für den Bug Report!
