### ISSUE TITLE
Strings only in original language - cannot translate

### ISSUE THREAD

**Issue by slawekmikula** [Akaflieg-Freiburg/enroute#125]
Some not translated strings i've found during PL translation (pushed to the enrouteText repository).

![untr-1](https://user-images.githubusercontent.com/157701/103170214-d85dcf00-4842-11eb-80cf-82dc9a30b761.png)
![untr-2](https://user-images.githubusercontent.com/157701/103170215-d98efc00-4842-11eb-808b-1ea37f3312c3.png)

**Comment by kebekus** [comment]
Thank you!

- I added translations for the "Total: …" text.
- The License text is found in Librarian.cpp and can be translated. As of now, the Polish translation is however a copy of the English text. A attach a screenshot of the Qt Linguist

![Bildschirmfoto von 2020-12-28 09-42-02](https://user-images.githubusercontent.com/5110976/103202129-e3236d00-48f1-11eb-993d-852c8fab8318.png)

**Comment by slawekmikula** [comment]
Ok, i'll translate it (it must be translated -> copied) before so it does not display in Qt Linguist as untranslated
