### ISSUE TITLE
Programm lässt sich auf Lenovo-Tablet mit android 7 nicht runterladen

### ISSUE THREAD

**Issue by knispe** [Akaflieg-Freiburg/enroute#127]
Das Programm lässt sich über den playstore nicht auf ein Lenovo-Tablet (Android 7) runterladen. Ist ein neueres Android erforderlich? 
Beste Grüße

**Comment by kebekus** [comment]
Wir fordern im Moment nur Android 5. Ich sehe, dass Sie den Report zwischenzeitlich geschlossen hatten, hat sich das Problem inzwischen vielleicht gelöst?

**Comment by knispe** [comment]
Leider nein, das Schließen erfolgte versehentlich. --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 30.12.20, 10:36 schrieb Stefan Kebekus <notifications@github.com>:

   
  Wir fordern im Moment nur Android 5. Ich sehe, dass Sie den Report zwischenzeitlich geschlossen hatten, hat sich das Problem inzwischen vielleicht gelöst?

**Comment by kebekus** [comment]
Mir ist unklar, ob ich hier helfen kann. Auf jeden Fall benötige ich folgendes:

- Genaue Bezeichnung des Gerätes (evtl. Screenshot von der betreffenden Seite der Einstellungen)
- Genaue Beschreibung der verwendeten Android-Version (auf jeden Fall Screenshot von der betreffenden Seite der Einstellungen)
- Genaue Beschreibung, wie das Herunterladen fehlschlägt, ebenfalls am besten mit Screenshots, die das Problem zeigen.

Sie können die Screenshots hier auf GitHub direkt hochladen.

**Comment by knispe** [comment]
Vielen Dank für Ihre Mühe,

 

ich denke das Problem hat sich erstmal erledigt .

 
 

Gesendet: Mittwoch, 30. Dezember 2020 um 11:27 Uhr
Von: "Stefan Kebekus" <notifications@github.com>
An: "Akaflieg-Freiburg/enroute" <enroute@noreply.github.com>
Cc: "knispe" <bhriwi@gmx.de>, "Manual" <manual@noreply.github.com>
Betreff: Re: [Akaflieg-Freiburg/enroute] Programm lässt sich auf Lenovo-Tablet mit android 7 nicht runterladen (#127)


 

Mir ist unklar, ob ich hier helfen kann. Auf jeden Fall benötige ich folgendes:


	Genaue Bezeichnung des Gerätes (evtl. Screenshot von der betreffenden Seite der Einstellungen)
	Genaue Beschreibung der verwendeten Android-Version (auf jeden Fall Screenshot von der betreffenden Seite der Einstellungen)
	Genaue Beschreibung, wie das Herunterladen fehlschlägt, ebenfalls am besten mit Screenshots, die das Problem zeigen.


Sie können die Screenshots hier auf GitHub direkt hochladen.

**Comment by kebekus** [comment]
Problem laut user erledigt.
