### ISSUE TITLE
User Feedback: enable entering the first place of a route as identical last place in map mode

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enroute#128]
Entering the route of a (e.g.) triangle flight in text mode works fine. If in map mode you try to add a place for the second time enroute only offers to drop that place from the route, not to add it again.

**Comment by kebekus** [comment]
Understood. Will work on this for one of the next version. I am however still unsure about an efficient GUI design that solves the issue…

**Comment by woodwind-enr** [comment]
Maybe someway like this:

![grafik](https://user-images.githubusercontent.com/65605447/103516847-78ce7780-4e71-11eb-9ece-bb3d971529e2.png)

**Comment by kebekus** [comment]
Fixed in version 2.3.
