### ISSUE TITLE
My Huawei 10 display is to small, I can't see the whole content

### ISSUE THREAD

**Issue by Ralph-krh** [Akaflieg-Freiburg/enroute#13]
My display on android Huawei 10 mobile phone is too small. I can't see the whole content.
Enclose I sent you a file with the view I have.
Maybe you can adapt the view?
![Screenshot_20200209_092835_de akaflieg_freiburg enroute-1](https://user-images.githubusercontent.com/60840785/74145909-31f3e580-4c00-11ea-9d91-f24aa25dbdf6.jpg)

**Comment by kebekus** [comment]
Bug confirmed. Will be fixed in version 1.2.0.

**Comment by kebekus** [comment]
Fixed in version 1.2.0.
