### ISSUE TITLE
User feedback: Track recording

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enroute#132]
the title says it all

**Comment by kebekus** [comment]
I will probably implement this feature, but this will take a long, long time.

**Comment by kebekus** [comment]
Hi,

unless someone joins in with the development, this feature will not be implemented soon. I have therefore turned it into a long-term project:

https://github.com/Akaflieg-Freiburg/enroute/projects/14

Best

Stefan.
