### ISSUE TITLE
User feedback: Show flight track

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enroute#133]
the title says it all

IMO this is - although nice - not a primary feature for a moving map application. If implemented, it would have to be optional in order not to overload the display/ms.

**Comment by kebekus** [comment]
Will probably implment, but this will take a long, long time.

**Comment by Dzordzik** [comment]
I don´t miss this feature. I think, same as previous user, it isn´t feature for not primary gliding app.

**Comment by kebekus** [comment]
Hi,

unless someone joins in with the development, this feature will not be implemented soon. I have therefore turned it into a long-term project:

https://github.com/Akaflieg-Freiburg/enroute/projects/14

Best

Stefan.
