### ISSUE TITLE
Waypoint names not showing in imported gpx route

### ISSUE THREAD

**Issue by a533** [Akaflieg-Freiburg/enroute#145]
**Describe the bug**
I share a gpx route from another app into Enroute. The route is imported in Enroute but instead of showing the names of the waypoints included in the gpx file (<name></name>  tag) it shows a generic label "Waypoint" in all of them.
**To Reproduce**
share a gpx file including names of waypoints into Enroute
**Expected behavior**
Waypoints names being shown.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
Redmi 9
Android 10

**Additional context**
n/a

**Comment by kebekus** [comment]
Thank you for your report!

The issue is already fixed; the bugfix will be contained in v2.3.0, which is scheduled for mid-February.

Best,

Stefan.
