### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ninelima** [Akaflieg-Freiburg/enroute#149]
I am attempting to build Enroute from source (tag 2.2.4)  for possible inclusion in the F-Droid FOSS repository. 

When running the ./buildscript-android-debug.sh
I get the following message:

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

Any suggestions?

**Comment by kebekus** [comment]
Deat Ninelima,

the script uses the standard Ninja build tool -- a more modern version of "make". Things should work fine if you simply install the Ninja program on your machine. Alternatively, cmake supports a large number of other build tools, including "make". Please let me know once **Enroute** is up-and-running on F-Droid. I will be happy to add a link to the homepage of the app.

Best,

Stefan.
