### ISSUE TITLE
Handy display ON while using App

### ISSUE THREAD

**Issue by Gerd-B** [Akaflieg-Freiburg/enroute#15]
It's not very practical that the display goes to the OFF Mode after some time and the Handy has to be unlocked via code or fingerprint.
My proposal for improvement : whenever the Handy is connected to external power (…… is loaded) , the display is in Always ON mode. Goggle Maps has the same function when navigating

**Comment by kebekus** [comment]
Feature will be implemented, but probably not before summer 2020. Please be patient until then.

**Comment by kebekus** [comment]
Will be implemented in a future version, but implementation will take time. Please be patient.

**Comment by kebekus** [comment]
Fixed in v1.4.0. Thank you for the report.
