### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by acrovato** [Akaflieg-Freiburg/enroute#150]
Hi Stefan,

André, a fellow Belgian pilot, reported a display bug. All the contextual text is in capital letter and displayed in a weird light font (see attached screenshot). I tried to reproduce the bug on my side, but did not manage (which is a kind of good news I guess).

According to André, the app was working normally up to this week, and he did not make any changes to his phone.
If I had to make a guess, I would say that the issue come from an update linked to Android, or something similar...

Here are the device information:
Device: One+ Nord 
OS: Android 10-5-10 Oxygen OS

![Screenshot_20210120-125226](https://user-images.githubusercontent.com/39187559/105633047-a72ee980-5e56-11eb-960f-1b98582a08f4.jpg)

**Comment by kebekus** [comment]
Hi,

I have looked at this and I am totally clueless. I have **no idea at all**. I have seen some devices with bitrot, which seems to happen much more often than thought. If bitrot is the problem, then uninstalling and re-installing the app will help. If this is a matter of Android fonts/configuration, then uninstalling and re-installing should not have any effect. Can you please ask your user to try this out? -- Thanks!

Best,

Stefan.

**Comment by andre-ada** [comment]
Hello friends,
Thank you for the message.
I followed the procedure suggested by Adrien and then I reinstalled Enroute. 
The presentation is unchanged: the letters are written in upper case and the data is barely readable (see previous screenshot).
The smartphone is very recent and all other apps are working fine.
Fortunately, everything else in Enroute works perfectly.
Thank a lot for your attention.
André

**Comment by kebekus** [comment]
Dear Andre-Ada,

thank you for your quick reply -- there go my hopes for a quick solution. I plan to release the next beta version later this week. Could you subscribe to the beta chanel on Google Play and try it out? The next version comes with a bit of a technology upgrade. Maybe that helps your problem…

Best,

Stefan.

**Comment by andre-ada** [comment]
Hello Stefan,

Thanks for your message.
I'm now beta.
Andre


Le mar. 26 janv. 2021 à 07:35, Stefan Kebekus <notifications@github.com> a
écrit :

**Comment by kebekus** [comment]
Have you had a chance to look at the new beta? Does the problem persist?

**Comment by andre-ada** [comment]
Hello Stefan,

Thank you for the message.

Update: no change in the display of texts, always in capital letters (see
screenshot).

Fortunately, this does not affect the correct functioning of the program.

For my part, I also asked the manufacturer of my recent OnePlus Nord
smartphone. This problem is unknown to them.

Thank you for your dedication to improving Enroute.

André

Le ven. 29 janv. 2021 à 08:42, Stefan Kebekus <notifications@github.com> a
écrit :

**Comment by andre-ada** [comment]
Hello Stefan, bonjour Adrien,

I just updated my smartphone with Androïd 11.
Good news! No more problem with the capital letters.
See annexed screenshot.
Have a nice day.
André

Le ven. 29 janv. 2021 à 09:43, Andre Darquennes <adarquennes@gmail.com> a
écrit :

**Comment by kebekus** [comment]
Thanks for all your help. To be honest, I still have no idea what's going on … I close the issue nonetheless.
