### ISSUE TITLE
IP change in settings for Wifi connected devices like Stratux

### ISSUE THREAD

**Issue by spuckebaer** [Akaflieg-Freiburg/enroute#156]
Connect the Stratux to enroute is workung well.
But it is needed to adapt the IP in Stratux. 
As it is more likely to move the tablet or smartphone arround the different planes it would be perfect to allow IP settings in Stratux

**Comment by kebekus** [comment]
@spuckebaer Thanks! I will look at this and try to find a solution that works automatically. This is however not my top priority at the moment (assuming that people who use Stratux are able to change the IP), so it might take a while before a solution is published.

**Comment by spuckebaer** [comment]
Thanks....very clear. not really mandatory but nice to have

**Comment by kebekus** [comment]
Starting with 2.6.0, the app will check several IP-Addresses simultaneously. Changing the IP address of the Stratux device is then no longer necessary. Please have a look at the current beta to try this feature.
