### ISSUE TITLE
Enroute Crash when Stratux connected

### ISSUE THREAD

**Issue by spuckebaer** [Akaflieg-Freiburg/enroute#157]
When Wifi connection to Stratux is established and Enroute is started is crashes. Restart of Enroute is solving the problem. (This is systematic at each start)
+ During yesterdays flight connection was 1 time lost even if wifi was connected

No failure message, just saw connection in Information "Trying to connect"

Lenovo Tablet lenovo tab m10 tb-x505f
Android 10

**Comment by kebekus** [comment]
@spuckebaer Thanks for the message! I will look at this with top priority. Regretfully, I have no idea at present why the app would crash, and any additional piece of information would help (screencast video, …). How well do you know android? Can you look at the log files and check if there is any useful information in there?

**Comment by spuckebaer** [comment]
I tried ADB but could not manage...if there are any proposals how to grab info from my tablet I am happy to provide.
I will also check tonight how I can make a video

**Comment by spuckebaer** [comment]
I habe currently a Power supply issue with my stratux and therefore I cannot reproduce the topic. If wifi is not connected to stratux start procedure is as normal without crash

**Comment by spuckebaer** [comment]
Still waiting for spareparts.....

**Comment by kebekus** [comment]
This problem still puzzles me. Let's wait for your spare parts and see…

**Comment by kebekus** [comment]
Dear spuckebaer,

can you please check if the problem still shows with the latest beta version of the app?

Thanks,

Stefan

**Comment by spuckebaer** [comment]
Still not received the new parts...friend of mine has a similar setup and it works for hinm,...so I concider it is on my side.Would propose to close and when I got the new parts I will check again and let you know if still the same, o.k.?

**Comment by kebekus** [comment]
Ok, will proceed as you suggest. Thanks for your help!
