### ISSUE TITLE
Green Target Arrow optical too similar to "Naturschutzgebiete"

### ISSUE THREAD

**Issue by spuckebaer** [Akaflieg-Freiburg/enroute#158]
Maybe to think about to change the colour of the arrow to ensure better visabiliy .
Fesable to add a flight path vector for the next minute (Due to direction and speed)?

**Comment by kebekus** [comment]
@spuckebaer I will look at this. It might take a while because some other issues have a higher priority at the moment.

**Comment by kebekus** [comment]
Kannst Du mir einen Screenshot schicken?

**Comment by spuckebaer** [comment]
![Screenshot_20210220-105233 (1)](https://user-images.githubusercontent.com/70006522/108689047-e7869380-74f8-11eb-8617-f6e1260fefc0.jpg)
Hab gerade kein Screenshoot aus der echten Skalierung beim fliegen, aber glaub für eine grobe Idee könnte es vielleicht schon reichen. Falls du mehr brauchst kann ich gerne am Freitag beim fliegen mehr machen

**Comment by kebekus** [comment]
Das Problem sollte sich mit der Anpassung der NRA-Farbe gelöst haben…
