### ISSUE TITLE
No Route displayed

### ISSUE THREAD

**Issue by spuckebaer** [Akaflieg-Freiburg/enroute#165]
Since last update (done this morning) I can neither on S9 nor on Lenovo Tablet display new routes.

E.g. when I select from a waypoint direct to, route is not displayed. Same if I create a route from route menu.

New installation did not solve the issue

Any idea?

**Comment by kebekus** [comment]
Thank you for the report. I fixed the issue and pushed an update to Google Play/Beta, where it will hopefully appear later today. If the issue persists, please feel free to re-open this issue.
