### ISSUE TITLE
Statusanzeige unlogisch

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enroute#172]
Info-Seite zeigt nach erfolgreicher Positionsbestimmung immer noch "Suche Position ..." in der Kopfzeile

![GPS-Status](https://user-images.githubusercontent.com/65605447/114989707-fe61ba80-9e97-11eb-94cc-d923e46097ee.jpg)

**Comment by kebekus** [comment]
Verstehe. Der Text zur Übersetzung war mißverständlich. Habe ich gerade korrigiert.

**Comment by kebekus** [comment]
Danke!
