### ISSUE TITLE
User Feedback: Phenomena after Update

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enroute#177]
Aus der Original-Mail:

Die App Enroute habe ich 2020 installiert und war damit sehr zufrieden. Es war alles so , wie es beschrieben wurde.
Nach Update`s war einiges verschwunden. Es fehlte der blaue Punk nach Standorterkennung ebenso der blaue Pfeil
im Flug .Der Geschwindigkeits-Wegbalken ist noch da. Der Modus Flugerkennung bleibt innaktiv.
Im Menü Information erfolgt die Meldung bei Satellitennavigation -Empfange keine Positionsdaten- .
Er findet aber meinen Standort, zeigt Geschwindigkei , Höhe und Richtung an ?
Alles so gewollt oder ein Fehler?
Mein Handy Sony Xperia  Android 7

**Comment by kebekus** [comment]
Closing because the sender did not reply to my e-mail requests.
