### ISSUE TITLE
Altitute in meters for gliders

### ISSUE THREAD

**Issue by MichaelMedek** [Akaflieg-Freiburg/enroute#181]
For gliders it would be usefull to see the current altitute in meters and also have the airspace altitudes in meters. Please add a toggleable ootion for that!

**Comment by kebekus** [comment]
Thanks! This feature will be implemented, but since I program the app alone and in my spare this, this will take some time.

**Comment by kebekus** [comment]
Dear MichaelMedek,

thanks again for your request. The feature will be implemented in version 2.14, which will likely appear before the christmas break.

Best,

Stefan.
