### ISSUE TITLE
Fule usage zero is not allowed (for gliders) 

### ISSUE THREAD

**Issue by MichaelMedek** [Akaflieg-Freiburg/enroute#183]
When planning a flight route I can not enter fuel usage of zero (since beeing a glider). But I must enter something to avoid Red errors that the route is incomplete.

**Comment by kebekus** [comment]
Dear MichaelMedek,

honestly, I never thought that Glider pilots would use this app... I see your problem and will come up with a solution. This will take some time, however. Meanwhile, I suggest that you enter a random number for fuel consumption and simply ignore the result.

Best,

Stefan,

**Comment by kebekus** [comment]
The issue has been solved. A fuel consumption of 0 l/h will be allowed starting from Version 2.8.1 of the app (which will appear on Google play in a week or so). Thanks again for your report!

Best

Stefan.
