### ISSUE TITLE
Flight direction arrow disappeared after creating and loading a route

### ISSUE THREAD

**Issue by hbeil** [Akaflieg-Freiburg/enroute#204]
Android 7 

The app was working fine  until I played with routes. 
As a side note I cannot use the direct to function anymore. 
The app reduced to a mere moving map with airspace and frequency information. 

habe die App dann neu installiert ohne Veränderungen .
Vielleicht ist es ja nur eine verklemmte Setting. Aber Settings erlaubt kein general "reset to Factory settings" oder so

Ähnliche Apps zeigen den Richtungspfeil auf dem gleichen Gerät. 

Gibt es hier eine Lösung, außer den Reset des Mobile Phones?

Beispiel im Flug:

![Screenshot_20210920-143927](https://user-images.githubusercontent.com/91286737/134574025-4905cf5e-7358-4236-995e-99732e29e49b.png)

**Comment by kebekus** [comment]
Dear hbeil,

from your description and from the screenshot, it seems that the problem has nothing to do with the flight route that you mentioned. The problem is that the app does not receive any positioning information from the Android system -- this is indicated for instance by the gray dot inside the moving map. Open the main menu and go to Information/Positioning for more information. This is also why "direct to" does not work.

I cannot tell from the distance why positioning does not work. Here are a few random guesses:

- You are inside a building and your sat receiver is not strong enough. -> Spend a few minutes outside to check (older versions of the app also used network information for position estimates, but newer versions use satellite only)
- Positioning is switched off in your device -> Check settings, switch it on again.
- Satellite navigation is broken in your device -> Try with another device to check. Note that other apps might still use the network for position estimated.

I am closing this issue now, because this does not seem like a bug in the app. Feel free to re-open if more information is available.

Best,

Stefan.

it seems that the app does not recieve any positioning information.

**Comment by hbeil** [comment]
Ähnliche Apps zeigen den Richtungspfeil auf dem gleichen Gerät.... zu gleicher Zeit.

Das heißt andere Apps können das, was Enroute plötzlich nicht mehr kann. Der angehängte Screenshot zeigt einen Flug in ca 2000 ft bei 95 kn. Die Moving Map moved ja mit, deshalb kann ich Positioning switched off ausschließen.
Ich will hier nicht meckern, sondern helfen ein vielleicht öfter auftretendes Problem zu lösen.

Ich werde mal die settings innerhalb Android checken. Bin mir aber sicher, die LOCATION info is on und Enroute allowed, wie sonst würde Enroute meine Position wissen uns die Karte verschieben?

Hartmut

**Comment by kebekus** [comment]
Lieber Hartmut,

Ok, verstanden. Mir war nach der ersten Nachricht nicht klar, dass das Problem im Flug auftritt. Ich hatte vermutet, Du probierst die App vom Sofa aus.

Dies ist jetzt ein sehr ungewöhnliches Problem, das ich so noch nicht gehört habe. Ich kann mir im Moment keinen rechtene Reim machen. Könntest Du die App bei nächst Gelegenheit noch einmal im Flug ausprobieren und folgendes nachschauen:

- Welche Programmversion verwendest Du genau?
- Ist die App mit einem Verkehrsdatenempfänger (z.B. FLARM) verbunden?
- Ist der Punkt, den Du für die "Eigene Position" siehst, blau oder grau?
- Was wird unter "Menü/Information/Positionsbestimmung" und "Menü/Information/Verkehrsdatenempfänger" angezeigt? -- Am besten zwei Screenshots.
- Tritt das Problem auch dann auf, wenn Du ein anderes Gerät verwendest?

Grüße,

Stefan.

**Comment by hbeil** [comment]
Hallo.
Verwendet wird Version 2.11.2 - siehe Screenshot
Kein Flarm verbunden
Grauer Punkt - siehe Screenshot
Keine Position wird im Menü angezeigt, aber Das Programm, wie auch alle anderen Programme auf dem Unit zeigen Position und Richtung
Andere Geräte haben das Problem derzeit nicht
![Screenshot_20210926-174342](https://user-images.githubusercontent.com/91286737/135025202-35574094-001d-40c3-82d1-472d631f77e8.png)
![Screenshot_20210926-174351](https://user-images.githubusercontent.com/91286737/135025207-5599a567-1a67-40f8-af53-11ebd3a3dc8b.png)
![Screenshot_20210926-174523](https://user-images.githubusercontent.com/91286737/135025209-a0cce36c-f4ff-4013-8b30-302e8fd06866.png)
.

**Comment by hbeil** [comment]
Ist schon komisch - das Programm sagt keine Positioning Information, jedoch lokalisiert mich direkt in Schönhagen Flugplatz. Ich konnte bei dem letzten Test nicht fliegen, sondern bin auf dem Flugplatz hin und her gewandert...

**Comment by hbeil** [comment]
Wie löse ich nun das SLL handshake Problem?

**Comment by kebekus** [comment]
Wäre es möglich, dass ich Du mir Dein Telefon ausleihst? Wenn ich das Gerät in der Hand habe und per "Android Developer Bridge" debuggen kann, kann ich den Fehler vielleicht finden. Ansonsten sitze ich vor meinem Schreibtisch, stochere im Nebel und bin relativ ratlos.

Ich verstehe, dass das evtl etwas viel verlangt ist ...

**Comment by hbeil** [comment]
It’s in the mail. Kommt hoffentlich schon Anfang nächster Woche. DHL Nr. 358315857549
Ich habe das Phone zurückgesetzt. Dann kannst du deinen eigenen Google account nehmen. Nach meinem Reset vorgestern ging die Verbindung zum GPS immerhin – aber der SSL Fehler wird dir auch begegnen.
Viel Glück.

Hartmut

**Comment by kebekus** [comment]
Kann SSl-Fehler reproduzieren, habe gleich noch anderes Problem gefunden und gefixt.

**Comment by hbeil** [comment]
“würde das Gerät gern noch einige wochen behalten”

@Stefan – klar geht das in Ordnung.

Hartmut

**Comment by hbeil** [comment]
Hallo Stefan.
Das Ende des Jahres naht. Brauchst du noch lange das Gerät?
Ich würde gerne zu Ende des Jahres die Dinge geordnet haben.

Danke


Hartmut

________________________________

**Comment by kebekus** [comment]
Lieber Hartmut,

danke für die Nachricht. Und danke für das Ausleihen des Gerätes. Ich bin mit deinem (und einigen anderen) Geräten fertig und habe mit den Rücksendungen begonne. Dein Gerät liegt schon auf meinem Schreibtisch. Kannst Du mir bitte kurz die Adresse nennen?

Grüße,

Stefan.

**Comment by hbeil** [comment]
Alles Klar Stefan, hier meine Postadresse

Hartmut Beil
Billy-Wilder Promenade 47
14167 Berlin

Hartmut

**Comment by hbeil** [comment]
Stefan - das Gerät ist gestern gut angekommen. Und ich habe gleich mal die app geladen. So weit keine Probleme.

Grüße Hartmut

**Comment by kebekus** [comment]
Lieber Hartmut,

ich bedanke mich für das Leihgerät! Da die Probleme wohl behoben sind, schließe ich den Report jetzt.

Bis zum nächsten mal!

Stefan.
