### ISSUE TITLE
Download of map data not possible

### ISSUE THREAD

**Issue by drnklemm** [Akaflieg-Freiburg/enroute#207]
**Describe the bug**
Habe soeben auf einem Samsung Galaxy S2 8 Zoll mit Android 7
das Programm installiert, die Liste der Luftfahrtkarten fehlt und kann nicht geladen werden. Habe enroute gelőscht und neu geladen, gleicher Fehler

"Fehler beim download der liste der luftfahrtkarten fehlgeschlagen Grund: Der SSL/TLS Hanshake schlug fehl, es kam keine verschlűsselte Verbindung zustande, Das Signal sslErrors() sollte gesendet werden"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kebekus** [comment]
Danke für die Meldung Der Fehler wurde von mehreren Nutzern berichtet, scheint aber nur auf älteren Samsung-Geräten aufzutreten. Ein Nutzer hat mir freundlicherweise sein Gerät zur Verfügung gestellt. Ich hoffe, den Fehler damit in der nächsten Woche reproduzieren, analysieren und beheben zu können. Ich melde mich, wenn es etwas Neues gibt.

Grüße,

Stefan Kebekus.

**Comment by drnklemm** [comment]
Dankeschön Stefan. --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 16.10.21, 12:25 schrieb Stefan Kebekus ***@***.***>:

   
  Nutzer melden, dass das Problem in Version 2.12.1 behoben ist.
