### ISSUE TITLE
Update Airspace NL

### ISSUE THREAD

**Issue by propellertje** [Akaflieg-Freiburg/enroute#218]
**Describe the bug**
Not exactly a bug but how to get an openAIP update concerning airspace change to be correctly shown in the EFN app.
There is no way to give airspace updates via the openAIP page and there is no response from openAIP.

**To Reproduce**
eg. EHLW coordinates EH-TRA11 are changed but EFN still uses the old data because openAIP does not let me input this nor is there a response from openAIP.

**Expected behavior**
Facilitating the process (may be a specific process between openAIP and EFN) how data updates input can be done.

**Screenshots**
none

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: LG Velvet (LM-G900EM
 - OS: Android 11
 - Browser: none
 - Version: none

**Additional context** 
At regular intervals the Eurocontrol AIS comes with update https://www.eurocontrol.int/articles/ais-online per country which might impact the use of EFN.
I do understand that this is not directly related to EFN itself but this might be an opportunity how to improve the updtae process between openAIP and EFN based on the update airrac data cycles from Eurocontrol. This will drastically further improve the use of this excellent and valuable app!

Kind regards Bernard

**Comment by kebekus** [comment]
Dear Bernard,

thank you for your report! As you probably saw, I forwarded your message to Stephan Besser at openAIP. I do not see anything else that I can do at the moment, so I am closing this issue here.

Best,

Stefan.
