### ISSUE TITLE
App does not update correctly 

### ISSUE THREAD

**Issue by requa3r0** [Akaflieg-Freiburg/enroute#226]
![Screenshot_20220424-182203](https://user-images.githubusercontent.com/16628002/164986143-8c7dc4ec-60dc-42ad-a1d6-dc41f65bacbd.jpg)
Hi

I have tried many times to update the app. 
Even the really hard way
Force stop, delete cache, delete storage, uninstall app.
The in the bootloader clear main cache.

When installing the newest version, it's still not working.

It does not open as a fresh install with map downloads etc.

Some data is til present! 

I have no top bar with the new info! 

The line for navigation is gone and the update is not properly applied.

What do I need to delete to properly wipe the old app? 

Look at the screen shot of the newest version.
I have a direct to set!

Kind regards Requaero

One plus 7 pro

NB the app install fine on a Samsung galaxy A71.. Without previous app data!

**Comment by kebekus** [comment]
Dear Requaero,

I am not sure I fully understand, so let me recapitulate

- You are missing the top bar with "remaining route info". Is that correct?
- Apart from the item above, is there any other problem that you have with the app?

In order to help me investigate the issue, can you please look at the main menu and tell me which version of the app you have? Also, if you open the "route" page from the main menu, is there a route that you have set? If yes, can you send me a screenshot of the route window?

Best,

Stefan.

**Comment by requa3r0** [comment]
Running latest version 2.16.0 
When installing after wipe of previous app and local delete of empty folder SD card . It did not ask for map download etc. 

Point 1.
Yes no top bar with any info.
Also Not when flying.

If setting a route.. With 2 wpt i get a line.. But not when selecting just one wpt and fly direct to. 

No line and no info on top bar. 
![Screenshot_20220424-194029](https://user-images.githubusercontent.com/16628002/164989447-c6d58b61-9772-4d17-944b-0272ebd8ac22.jpg)
![Screenshot_20220424-194023](https://user-images.githubusercontent.com/16628002/164989448-0a649889-3d3a-4bfe-aeca-8d6a7c2840f8.jpg)

**Comment by requa3r0** [comment]
![Uploading Screenshot_20220424-194656.jpg…]()

**Comment by requa3r0** [comment]
I only see a line with 2 wpt.. Still no top bar. 
NB. I kind of agree with previous issue regarding the line would stand out better in magenta. 


![Screenshot_20220424-194656](https://user-images.githubusercontent.com/16628002/164989590-75f63726-2973-43be-b127-48becf00ca07.jpg)

**Comment by kebekus** [comment]
Actually, in your picture there **is** a top bar. It's the text "More than 3 nm off route". This text is shown if are more than 3 nm away from the route. At that distance, you are probably not following the route and it is often hard (or impossible) to guess what your intentions are and how long your flight will take. Move back closer to the route and the text in the top bar will change accordingly.

**Comment by requa3r0** [comment]
You are right.
Perhaps my full wipe attempt did solve the issue. 
I have not been able to make the app work for quite some time.

Setting a closer user wpt and then an airport as destination, does give me a route line and a direct line.

Still don't get anylines when just going direct to a point though. 
Perhaps I need to be moving?
Ill test in the car tomorrow.

**Comment by kebekus** [comment]
Dear [requa3r0](https://github.com/requa3r0),

ok. It seems that there are three separate issues:

- Uninstalling the app does not wipe all the data. I have opened a new bug report for this issue.
- The "remaining route info" is not what you expect; this seems a non-issue now.
- The route is not shown when going "direct to". This is a bug. I have been able to reproduce this bug on my machines. I have opened a new bug report for this issue and will try to fix this bug as soon as possible.

Thank you for your report! As soon as I have opened the new bug reports, I will close this one and then resolve the issues one-by-one.

Best,

Stefan.

**Comment by kebekus** [comment]
Dear [requa3r0](https://github.com/requa3r0),

thanks again. I have opened separate new bug reports for each of the issues that you describe. Please subscribe to them, so I can report progress and contact you.

I am closing this report now.

Best,

Stefan.

**Comment by kebekus** [comment]
@[requa3r0](https://github.com/requa3r0): can you please have a look at the following issues that I opened in response to your request?

- [Issue #228](https://github.com/Akaflieg-Freiburg/enroute/issues/228)
- [Issue #227](https://github.com/Akaflieg-Freiburg/enroute/issues/227)

You need to subscribe to those issues, so we can communicate. Subscription is done via the bar on the right side of the screen, under 'notification'. In each of these issues, can you add a quick comment, so I can see that you are there? -- Thanks!
