### ISSUE TITLE
Make the app compatible to pickup traffic information

### ISSUE THREAD

**Issue by shortyxs** [Akaflieg-Freiburg/enroute#23]
Great work with the App so far!

I'd  like to see traffic beeing displayed from a source, such as Stratux.
The team ofthe [Stratux Europe Edition](https://github.com/b3nn0/stratux), is doing an awsome job, gaining the information via ADS-B and  Flarm, to provide it to a Map App, like enroute.
As Straux is also Open Source, I'd prefere this over any other commercial solution.

**Comment by kebekus** [comment]
Dear Mr. Schroeder,

thank you for this suggestion. I have not yet made up my mind if (and to what extend) I will include this feature, as there are many outstanding issues that are probably more urgent. I shall come back to you in a while. Would you be willing to help with the implementation?

Best - Stefan Kebekus.

**Comment by joachimwe** [comment]
The Stratux Support is included since 2.5

**Comment by kebekus** [comment]
As joachimwe pointed out: Stratux devices are supported now. I am closing this issue. Thank you for your help!
