### ISSUE TITLE
Please make the app available outside of googles Playstore.

### ISSUE THREAD

**Issue by shortyxs** [Akaflieg-Freiburg/enroute#24]
Can you please make the App available not only on googles Playstore?

It would be a nice benfit if you could provide it on f-droid for example or as an APK download,within the Github Releases. Not for the average user but at least for those that know what they are doing with that.
I hope once it is compiled an published on the playstore, it will be no big deal to distribute it elsewhere.

**Comment by kebekus** [comment]
Dear Mr Schroeder, 
thank you for this suggestion. I am very sympathetic to the idea. However, I do not wish to add another long-time commitment to my portfolio. Would you be willing to take the job to maintain the app's presence on f-droid and to regularly upload new versions of the app there? If so, please contact me at stefan.kebekus@gmail.com. I will be closing this issue until I hear from you.
Best,
Stefan.
