### ISSUE TITLE
GPS-Empfänger

### ISSUE THREAD

**Issue by Petersen78** [Akaflieg-Freiburg/enroute#247]
Trotz aktivierter Standortbestimmung in ENR FLIGHT INFORMATION APP erzeugt die App die Fehlermeldung, dass keine GPS-Positionsdaten empfangen werden

**Comment by kebekus** [comment]
Lieber Petersen78,

entschuldigen Sie die späte Antwort -- ich bin zurzeit beruflich auf Reisen,

Ich helfe Ihnen gern, benötige dazu aber viel mehr Informationen.

- Welche Version der App verwenden Sie?
- Welches Betriebssystem verwenden Sie? Desktop? Android?
- Können Sie den Fehler genauer beschreiben? Vielleicht mit einem Screenshot oder einem Screencast Video?
- Funktionieren gleichzeitig andere Apps mit Positionsbestimmung?
- Sind Sie im Freien? Die App verwendet nur Satellitennavigation, die in Innenräumen meist nicht geht.
- Was wird angezeigt, wenn Sie im Hauptmenü die Seite "Info/Positionsbestimmung" wählen? Auch hier ist vielleicht ein Screenshot hilfreich.

Beste Grüße,

Stefan Kebekus.

**Comment by kebekus** [comment]
Ich schließe diesen Vorgang, weil ich noch keine Antwort bekommen habe. Falls Sie noch antworten, öffne ich den Vorgang gern wieder.

**Comment by Petersen78** [comment]
Lieber Herr Stefan Kebekus, die Antwort haben Sie mir jetzt schon gegeben,  ich habe die App in einem Innenraum ausprobiert und dann logischerweise keine Positionsdaten empfangen.  Im Freien , wo es einzig gehen muss,  geht es natürlich...Vielen Dank, Peter Petersen --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 22.06.22, 17:02 schrieb Stefan Kebekus ***@***.***>:

   
  Lieber Petersen78, 
  entschuldigen Sie die späte Antwort -- ich bin zurzeit beruflich auf Reisen, 
  Ich helfe Ihnen gern, benötige dazu aber viel mehr Informationen. 
   
   Welche Version der App verwenden Sie? 
   Welches Betriebssystem verwenden Sie? Desktop? Android? 
   Können Sie den Fehler genauer beschreiben? Vielleicht mit einem Screenshot oder einem Screencast Video? 
   Funktionieren gleichzeitig andere Apps mit Positionsbestimmung? 
   Sind Sie im Freien? Die App verwendet nur Satellitennavigation, die in Innenräumen meist nicht geht. 
   Was wird angezeigt, wenn Sie im Hauptmenü die Seite "Info/Positionsbestimmung" wählen? Auch hier ist vielleicht ein Screenshot hilfreich. 
   
  Beste Grüße, 
  Stefan Kebekus.
