### ISSUE TITLE
doc: Explain the black+white line when moving

### ISSUE THREAD

**Issue by rawtaz** [Akaflieg-Freiburg/enroute#248]
**Is your feature request related to a problem? Please describe.**
First of all, what an amazing app. So simple, clean and non-convoluted. Kudos to the developers!

Second, I have yet to try this app on a real flight, but today I just took it for a brief spin and noticed that when the airplane is moving, there's a five-segment black and white line in the heading direction of the airplane (or is it in the track direction?).

I'm *guessing* that this line 1) adjusts its length based on how fast the airplane is currently moving (ground speed), and 2) that each segment represents one minute of flying. So effectively this line and its segments is about seeing how far you'll get at the current ground speed, is this correct?

**Describe the solution you'd like**
I haven't been able to find an explanation for this black-white five-segment heading line in the docs. Possibly I just missed it, but if not, can someone please either just commit a change to the docs that explains this line and how to interpret it, or sum it up here and I'll be happy to open a PR for the docs.

**Describe alternatives you've considered**
I tried to use brain power to determine what this was for and what to make of it, but I'm pretty sure the feature suggestion above would be a much safer approach to getting it right.

**Additional context**
None, but let me know if I need to clarify anything.

**Comment by kebekus** [comment]
Thanks! I will consider your suggestion, but I am rather busy and need some time. I will come back to you as soon as possible.

**Comment by rawtaz** [comment]
I'd be happy to file a PR, as long as someone can verify what that line actually means.

**Comment by rawtaz** [comment]
@kebekus Thanks a lot! That text change clarifies it even further. I had honestly not found that text in the docs before, the thought of looking in a "Before you fly" section for info on what the GUI elements look like/are about *during* flight did not cross my mind. Either way, feel free to close this issue, the fix is in commit c2b0ec0 .
