### ISSUE TITLE
Keep current name of route when displaying rename dialog

### ISSUE THREAD

**Issue by rawtaz** [Akaflieg-Freiburg/enroute#250]
**Is your feature request related to a problem? Please describe.**
When in the library you click to rename a route, you currently have to type the entire name all over again. This is very cumbersome when you just want to change part of the name.

**Describe the solution you'd like**
Make the old/current name of the route be the prepopulated value when displaying the rename dialog, such that one can just edit the current name.

**Describe alternatives you've considered**
I tried copying the old name but there's no way to do that it seems.

**Additional context**
None.

**Comment by kebekus** [comment]
Thank you for this report. I will look into this and implement your suggestion ASAP.

**Comment by kebekus** [comment]
Thanks again. The suggestion is implemented in version 2.18.1, which I uploaded to Google Play a few minutes ago. It should become available withing the next 24h.

Best wishes,

Stefan.
