### ISSUE TITLE
Modify graphics for ATZ

### ISSUE THREAD

**Issue by TTC70** [Akaflieg-Freiburg/enroute#264]
It would be great if ATZs limits were "inner shadowed" with blue color (I haven't seen this color combination on the maps, so it might uniquely identify an ATZ).

**Comment by kebekus** [comment]
@TTC70 This feature will be implemented with the next version of the app, which will likely appear in late October 2022.

**Comment by kebekus** [comment]
@TTC70 Done. Can you please update the app to 2.21.0, update the maps and confirm that everything is ok now? -- Thanks.
