### ISSUE TITLE
Enroute flatpak not starting in Linux Plasma Wayland session

### ISSUE THREAD

**Issue by AgentSmith0** [Akaflieg-Freiburg/enroute#287]
**Describe the bug**
When I try to start the Enroute flatpak I get the following error message:
```
$ flatpak run de.akaflieg_freiburg.enroute
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""                                  
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.                  
                                                   
Available platform plugins are: minimalegl, eglfs, linuxfb, offscreen, minimal, vkkhrdisplay, vnc, xcb.                                                  
```

**To Reproduce**
1. Start the flatpak (`flatpak run de.akaflieg_freiburg.enroute`)
2. See the error message

**Expected behavior**
Enroute starts.

**Desktop (please complete the following information):**
 - OS: Manjaro ARM (Linux)

**Smartphone (please complete the following information):**
 - Device: PinePhone Pro
 - OS: Manjaro ARM

**Additional context**
Somehow, this only happens on my PinePhone Pro now, my laptop once had the same issue, but the error has gone away by now.

**Comment by kebekus** [comment]
@AgentSmith0 Thank you for your report! This issue is challenging to investigate because I have no PinePhone. Can you run the app with the QT_DEBUG_PLUGINS flag set and send me the output? This can be done with the following command line:

```
QT_DEBUG_PLUGINS=1 flatpak run de.akaflieg_freiburg.enroute
```

Best,

Stefan.

**Comment by kebekus** [comment]
@AgentSmith0 Thank you. Unfortunately, this is not nearly as helpful as I had hoped :-( To make matters worse, I am currently under high pressure with my job. Please give me a few days to think about the next steps.

**Comment by kebekus** [comment]
@AgentSmith0 I have fixed a similar issue. Can you please check if the problem has been resolved with the last flatpak update of the app? -- Thanks.

**Comment by kebekus** [comment]
@AgentSmith0 Thanks for the report!
