### ISSUE TITLE
Bug with running in the split-view mode

### ISSUE THREAD

**Issue by fellow7000** [Akaflieg-Freiburg/enroute#288]
**Describe the bug**
After upgrade to Android 13 there is a bug once the App is running in the split-mode view: visualization is not correct and does not scale properly to the available screen. This happens mostly on devices with screen size pess than 8" . On 11" works fine.

**To Reproduce**
1. Go to start an application in split moe view along with another applicatio n in landscape mode
2. Try to opean any information dialog (eg. Airfield information)

**Expected behavior**
Information dialog should scale to the available screen but it does not

**Screenshots**
See screenshort where enroute is running along with an checklist app
![Screenshot_20230321_145939](https://user-images.githubusercontent.com/46420380/226632007-3a35b66c-e967-4216-936f-619ef28813ce.jpg)

**Desktop (please complete the following information):**
 - Android

**Smartphone (please complete the following information):**
 - Device: see above

**Additional context**
N/A

**Comment by kebekus** [comment]
Thank you for the report. I had never used the split view myself (and did not even know it existed) until you sent this message. I will investigate the issue, but I probably need a few days or weeks.

**Comment by kebekus** [comment]
Update: I have learned about the split view mode and can reproduce the issue on my devices.

**Comment by fellow7000** [comment]
Danke!

The reason for the split view: i combine your navi app with my app for electronic checklists (also a free app). This combination allows me to fly paperles.

I have a feeling, then enRoute worked fine with Android 12 but recently after upgrade to Android 13 it broke.

Felle free to contact me for beta testing if needed :)

Gruss aus EDTQ!

**Comment by kebekus** [comment]
@fellow7000 Ich melde mich, sobald ich etwas zum testen habe. Falls die Sache unter Android 12 je funktioniert hat, dann wohl nur aus Zufall. Bis vor wenige Tage wusste ich nicht einmal, dass es einen "split view mode" überhaupt gibt!

**Comment by kebekus** [comment]
The first implementation of split-view support works, but with many rough edges.

**Comment by kebekus** [comment]
Thanks again for your report. I have uploaded version app version 2.26.06 to Google Play, which (hopefully) solves the issue.

@fellow7000 I have little experience with "split view" and have only a few devices where I can test the feature. Can you please download 2.26.06 and give it a thorough test?

At present, 2.26.06 is available to beta testers only. If you are not a beta tester, please use the following link to join the beta program at Google Play.

- https://play.google.com/apps/testing/de.akaflieg_freiburg.enroute

You can, of course, leave the program anytime you like.

Best wishes · Looking forward to your feedback,

Stefan.

**Comment by fellow7000** [comment]
Thanks a lot for a fast reaction and providing of a beta version. I've just checked it on two devices (Handy Galaxy S10 Lite w. Android 13 ca 6.4" display and Galaxy Tab 3 Active w. Android 13 ca 8" display) and it worked correct in the split view - see a screenshot from Tab 3.

![Screenshot_20230329_094055](https://user-images.githubusercontent.com/46420380/228462774-b95a8cd8-8031-44b9-b37b-e9b721bbe995.jpg)

I hope, the fix will work also in the air.

**Comment by kebekus** [comment]
@fellow7000 Very well, I will releaser Version 2.26.06 now an close this issue.

Thank you very much for the report. Please keep reporting any issues that you may find!
