### ISSUE TITLE
Dialog only scrollable with 4 finger gesture

### ISSUE THREAD

**Issue by joachimwe** [Akaflieg-Freiburg/enroute#290]
Hi, 

- Auf meinem Phone lässt sich die Listview der Dialoge nur mit 4 Fingern scrollen.  Im Flug ist das hinderlich - eine einfachere Fingergeste (z.B.1 Finger scroll-Geste) wäre hilfreich.
- Notam Listview - Scrollen bei vielen Einträgen (z.B. LFST)  funktioniert nicht
- z.B. bei längeren Listen z.B. Strasbourg Entzheim (LFST) sind Einträge nicht sichtbar. Wenn Sie wie im Screenshot sauber unten enden, fällt es leider gar nicht auf, dass etwas fehlt. --> vielleicht kann man mit einem Symbol z.B. Pfeil nach unten anzeigen, dass die Liste länger als die darstellbare Fläche ist.

Falls es einen Workaround gibt bzw. es so intendiert ist, danke für eine kurze Rückmeldung.

Tolle Arbeit
Joachim
Samsung Android A71

![enroute-dialog-screenshot](https://user-images.githubusercontent.com/9807029/227794434-ade78fb3-7e5d-4747-8c9d-528a576f8efc.png)

**Comment by kebekus** [comment]
@joachimwe 

Lieber Joachim,

Danke für die Meldung!

- Zu Punkt 1+2: Ich bin verwirrt, weil ich auf meinem Gerät stets nur mit einer 1-Finger Geste scrolle. Ich wusste gar nicht, dass es eine 4-Finger-Geste gibt. Der Screenshot scheint ein Gnome-Desktop zu zeigen. Auf welcher Platform tritt das Problem denn genau auf?

- Zu Punkt 3: Gute Idee, werde ich implementieren. Ich habe für diesen Punkt einen neuen Eintrag aufgemacht: https://github.com/Akaflieg-Freiburg/enroute/issues/291

Grüße,

Stefan.

**Comment by joachimwe** [comment]
Hallo Stefan,

- zu 1) Voraussetzung - lange Listviews z.B. LFST: mein Phone scrollt nur mit 4 Fingerspitzen auf dem Screen (Items sind reine readonly Elemente)
- zu 2) Notams - z.B. bei LFST: Items sind clickable (gelesen bzw. nicht gelesen); hier funktioniert scrollen nur, wenn ich links und rechts am "Rahmen" mit 4 Fingerspitzen (z.B. 2 links, 2 rechts außerhalb der clickable area, rote "Punkte" sind meine Finger :-)) 

Auf einem alten S2 Tablet (Samsung) funktioniert das Scrollen mit einem Finger problemlos.

Ich hoffe, dass dafür eine Lösung gefunden werden kann.

Danke, Joachim

A71 - Android 13 

![Screenshot_20230327_141455](https://user-images.githubusercontent.com/9807029/227952724-1754c26a-d9f1-478f-8687-be20817890bb.jpg)

![grafik](https://user-images.githubusercontent.com/9807029/227952507-5549790e-a3a5-4df9-af73-b217912b39d6.png)

**Comment by kebekus** [comment]
@joachimwe Hallo, ich habe inzwischen Version 2.26.7 zu Google Play hochgeladen. Die Version enthält eine Upgrade der zugrundeliegenden Qt-Bibliotheken auf Version 6.4.3. Kannst Du bitte einmal testen, ob Dein Problem damit immer noch auftritt? -- Danke!

**Comment by kebekus** [comment]
@joachimwe Der Vorschlag mit dem ListView ist implementiert und wird in der nächsten Version enthalten sein.

**Comment by kebekus** [comment]
Closed for inactivity.

@joachimwe Please feel free to re-open if your problems persist.
