### ISSUE TITLE
Unable to run flatpak on desktop Linux (Session management error)

### ISSUE THREAD

**Issue by DeniTCH** [Akaflieg-Freiburg/enroute#293]
**Describe the bug**
I am unable to run the flatpak on desktop Linux (Pop OS 22.04LTS). The app window never appears. There seems to be some kind of a permissions issue.

I get the following output in the terminal:

```bash
flatpak run de.akaflieg_freiburg.enroute 
qt.gui.icc: fromIccProfile: failed size sanity 2
qt.gui.icc: fromIccProfile: failed size sanity 2
Gtk-Message: 19:45:50.038: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:45:50.038: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
[ INFO ]  "{unknown}[General]: GPU Identifier: AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.49, 6.2.6-76060206-generic)"
qt.positioning.geoclue2: Unable to start the client: "org.freedesktop.DBus.Error.AccessDenied" "Geolocation disabled for UID 1000"
```

**To Reproduce**

See above.

**Expected behavior**
I expect the app to start

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Pop OS 22.04LTS
 - Browser: Brave 
 - Version 1.38.119

**Comment by kebekus** [comment]
Thank you for the report. The message arrived, but I am overwhelmed with my job now. Please give me a few days, and I will get back to you as soon as possible.

**Comment by kebekus** [comment]
@DeniTCH I apologize for the late answer; we're spending a few days with the family in London. I have a (technically much simpler) calculator app that uses the same underlying technology platform,

- https://flathub.org/apps/details/de.akaflieg_freiburg.cavok.add_hours_and_minutes

Please check if the problem shows with that app as well. This might be much easier to debug. Also, there are two graphical systems in Linux: X11 and Wayland. Could you let me know which one you are using? Some systems allow choosing the GUI system at login. If that is also true on your system, please check if the problem shows for the two systems or just for one of them.

I appreciate your help!

**Comment by kebekus** [comment]
I found that the app does work fine when started from the command line like so:

```
QT_QPA_PLATFORM=xcb flatpak run de.akaflieg_freiburg.enroute
```

I am still trying to make sense of this…
