### ISSUE TITLE
Coordinates 

### ISSUE THREAD

**Issue by P4U1x** [Akaflieg-Freiburg/enroute#327]
Waypoint coordinates are displayed in 100th and not in 60th (minutes). Therefore, they aren't usable for creating an official flight plan.

**Comment by kebekus** [comment]
@P4U1x I am sorry for the late answer - I am on vacation right now. You can get waypoint coordinates in Degrees and Minutes: open the waypoint editor (where the coordinates are shown) and choose the desired format. I have attached two screenshots for illustration.

Please also have a look at the following request, which will be implemented in one of the next program versions; this will hopefully make it **much** easier to file official flight plans:

- https://github.com/Akaflieg-Freiburg/enroute/issues/282

Thank you for your report! I am closing this issue now. Please feel free to re-open if you believe this answer does not adequately address your problem.

Best,

Stefan 


![Bildschirmfoto vom 2023-05-31 07-03-48](https://github.com/Akaflieg-Freiburg/enroute/assets/5110976/efab1855-6d8a-4ac3-8556-0a32ea96140d)

![Bildschirmfoto vom 2023-05-31 07-03-57](https://github.com/Akaflieg-Freiburg/enroute/assets/5110976/0fc61569-c667-4d1b-8127-42ad9beaf915)
