### ISSUE TITLE
Text in waypoint description dialog is cut off

### ISSUE THREAD

**Issue by kebekus** [Akaflieg-Freiburg/enroute#334]
Simon has sent me the following screenshot (from iOS, 2.27.1)

![grafik](https://github.com/Akaflieg-Freiburg/enroute/assets/5110976/d42a1c67-4125-4e64-888b-05fb3f948d0f)

**Comment by kebekus** [comment]
I cannot reproduce the problem. Here's what it looks like for me.

![Bildschirmfoto vom 2023-07-02 20-24-44](https://github.com/Akaflieg-Freiburg/enroute/assets/5110976/ba3413ea-e451-4e0f-b385-f04373787bc8)

**Comment by kebekus** [comment]
Simon:  tritt auf einem iPhone 8 auf, auf meinem 14 nicht. 

App neu starten -> Flugplatz öffnen => Kein Bug
Schließen -> Dialog erneut öffnen ⇒ Bug
Landscaper drehen ⇒ nein Bug
Zurück Portrait drehen ⇒ kein Bug
Dialog erneut öffnen ⇒ Bug

**Comment by kebekus** [comment]
@schneisi Existiert das Problem noch?

**Comment by schneisi** [comment]
Kann ich mit einem aktuellen 2.30.X Build auf dem betroffenen Gerät nicht mehr reproduzieren

**Comment by kebekus** [comment]
@schneisi Besten Dank, ich schließe den Fall dann.
