### ISSUE TITLE
[Feature idea] Search functionality for airports?

### ISSUE THREAD

**Issue by AgentSmith0** [Akaflieg-Freiburg/enroute#357]
**Is your feature request related to a problem? Please describe.**
Currently, you need to search on the map for a specific airport.

**Describe the solution you'd like**
Sometimes it could be easier to search for an airport using it's name or an ICAO name.

**Comment by kebekus** [comment]
This issue duplicates [this issue](https://github.com/Akaflieg-Freiburg/enroute/issues/356). It will be implemented, but this will take time. We do not have enough manpower and therefore need to prioritize.

**Comment by TTC70** [comment]
Hello,
I believe you can go around the problem if you go in "Flight plan and wind", use the feature "Add a waypoint", type the ICAO of the airport you are looking for, and you find it.
No need to remark that the maps of the related country must be installed on your device.

Generally speaking, let's remember that Enroute is a navigation app ("free/ads free"), then it makes sense to find the airport/waypoint on the flight planning menu.
This does not mean that a "Search" feature should not be implemented. Let's also remember that @kebekus is alone in programming/updating the app, hence he needs to prioritize and time.

**Comment by kebekus** [comment]
Implemented. Will appear in next release.
