### ISSUE TITLE
Own map display is very fuzzy despite mbtiles providing zoom 11-12 level

### ISSUE THREAD

**Issue by Flying-Roger** [Akaflieg-Freiburg/enroute#366]
**Describe the bug**
Zoom levels above z10 are seemingly ignored by Enroute.
Maps using zoom levels 11, 12 becomes very fuzzy when zooming in.

**To Reproduce**
1. Select mbtiles file using only zoom 11 or 12 
2.  "Open with" enroute
3  Displayed map is empty
or
1. Select mebtiles files using zooms 8-12
2. "Open with" enroute
3.  Map is displayed, but becomes very fuzzy when zooming in despite providing zoom 11, 12 in the mbtiles file

**Smartphone (please complete the following information):**
 - Device: Samsung A34
 - OS: Android 14

**Comment by kebekus** [comment]
@Flying-Roger Understood. I apologize for not being very responsive over the holidays … you know how it is.

Can you give me access to the MBTILES file in question?  -- Thanks.

**Comment by Flying-Roger** [comment]
Hello Stefan,

 

Thank you for your fast answer.

 

I detected the fuzzy problem importing a big map prepared with MOBAC.
However, I narrowed the search preparing small mbtiles with different zoom level (only one level in each file).

Here is one with only zoom 12.

 

Kind regards,

Roger

 

De : Stefan Kebekus 
Envoyé : samedi 6 janvier 2024 17:17
À : Akaflieg-Freiburg/enroute ***@***.***>
Cc : Flying-Roger ***@***.***>; Mention ***@***.***>
Objet : Re: [Akaflieg-Freiburg/enroute] Own map display is very fuzzy despite mbtiles providing zoom 11-12 level (Issue #366)

 

 <https://github.com/Flying-Roger> @Flying-Roger Understood. I apologize for not being very responsive over the holidays … you know how it is.

Can you give me access to the MBTILES file in question? -- Thanks.

**Comment by kebekus** [comment]
@Flying-Roger EMail attachments do not work in GitHub. Please upload the file (the small and the big one) [here](https://v2202001110709105590.ultrasrv.de/nextcloud/index.php/s/t2j4fCDot4gF3Rf). Please let me know once you are done, so I can close the upload folder.

**Comment by Flying-Roger** [comment]
I uploaded the two small examples (z11 and z12), as well as a bigger map (z7-16).
You will notice that Enroute only uses z7-10 of the latter, ignoring all deeper zoom levels.

**Comment by kebekus** [comment]
Files received. Where in all the world are you and what region do these maps cover?

**Comment by Flying-Roger** [comment]
Oops, sorry.
I thought that tiles geolocalisation would allow you to find the area.

The map with zoom level up to 16 is centered on Bütgenbach (Belgium).

N 50:24:54.00  E 006:16:35.00

Kind regards
Roger


(Envoyé de mon smartphone)

Le dim. 7 janv. 2024, 14:36, Stefan Kebekus ***@***.***> a
écrit :

**Comment by Flying-Roger** [comment]
I had a look into the source code and found out that min and max zoom levels have to be provided in the metadata.
Seemingly mbtiles generated using MOBAC do not contain this information.
I have now patched my mbtiles files and the display is no longer fuzzy.
Problem solved; maybe a note about mbtiles metadata in the manual would help.

**Comment by kebekus** [comment]
@Flying-Roger Thank you for the insight, and please apologize for my late answer. I checked the [specification document](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md) for the MBTILES format today. To my surprise, I found that the metadata fields "minzoom" and "maxzoom" are not mandatory. I will add a workaround code, so **Enroute** extracts "minzoom" and "maxzoom" values from the "tiles" table if they are not provided explicitly in the file.

**Comment by Flying-Roger** [comment]
Thank you !

Roger

 

De : Stefan Kebekus 
Envoyé : mercredi 24 janvier 2024 07:43
À : Akaflieg-Freiburg/enroute ***@***.***>
Cc : Flying-Roger ***@***.***>; Mention ***@***.***>
Objet : Re: [Akaflieg-Freiburg/enroute] Own map display is very fuzzy despite mbtiles providing zoom 11-12 level (Issue #366)

 

@Flying-Roger <https://github.com/Flying-Roger>  Thank you for the insight, and please apologize for my late answer. I checked the specification document <https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md>  for the MBTILES format today. To my surprise, I found that the metadata fields "minzoom" and "maxzoom" are not mandatory. I will add a workaround code, so Enroute extracts "minzoom" and "maxzoom" values from the "tiles" table if they are not provided explicitly in the file.

**Comment by kebekus** [comment]
(Hopefully) fixed in 2.30.4, which is to appear on Google Play later today.

@Flying-Roger Thank you for your help!
