### ISSUE TITLE
Question: Import .cup files on iOS devices?

### ISSUE THREAD

**Issue by schluetb** [Akaflieg-Freiburg/enroute#373]
Is it possible to import .cup files on iOS devices, and if so, how do you do it?
Chapter 3.6.4 briefly describes the procedure for Andriod and Linux, but not for iOS.
I would like to import the data from https://landewiesen.streckenflug.at/
---
Is this the right way to ask questions like this one?
---
Thanks for your work!

**Comment by schneisi** [comment]
The latest iOS Release, which includes the import of .cup files, will be available for download later today.

**Comment by kebekus** [comment]
Fixed.
