### ISSUE TITLE
Maps partially visualized

### ISSUE THREAD

**Issue by TTC70** [Akaflieg-Freiburg/enroute#376]
**Describe the bug**
Only on tablet (only recently): when you go out from your country (where you can see airports, airfields, and so on) the map is partially loaded (see screenshot here below).
I have added also the screenshot of the same area from the phone just for comparison:

**To Reproduce**
1. unzoom until the "-" (minus) button is not visible anymore.
2. scroll the map outside the borders (for instance, towards another downloaded map).
3. The map is partially visible.

**Expected behavior**
Usually the basic map is visible (see screenshot from the mobile phone - Samsung Galaxy S10).

**Screenshots**
![Screenshots](https://github.com/Akaflieg-Freiburg/enroute/assets/90395124/4c282d09-ad36-46d5-865f-e73c06a0fb3c)

Cheers

**Comment by kebekus** [comment]
@TTC70 Understood. This does not affect the app's usability, correct? I will, therefore, classify this as "enhancement" with low priority. I hope you do not mind.

**Comment by TTC70** [comment]
I confirm the issue does not affect app's usability.
Funny thing, the issue related to basic map disappearing happens only then
I un zoom with the "-" (minus) button. It does not happen with "pinch and
unzoom" fingers action.

Being a beta tester I have to report it 😊😊

Ciao!

Il Dom 11 Feb 2024, 08:58 Stefan Kebekus ***@***.***> ha
scritto:

**Comment by kebekus** [comment]
> Being a beta tester I have to report it 😊😊

Absolutely! Without help, we would never find all these issues.

Thanks - Stefan.

**Comment by kebekus** [comment]
(Hopefully) fixed in 2.30.4, which is to appear on Google Play later today. Thanks for all your help!
