### ISSUE TITLE
Icon on macOS does not always show correctly

### ISSUE THREAD

**Issue by mipastgt** [Akaflieg-Freiburg/enroute#392]
When the application is running on macOS, the app-icon in the dock is showing correctly but as soon as the application is terminated the icon changes to something undefined. Tested on macOS (Intel) Sonoma 14.4.

**Comment by kebekus** [comment]
I can confirm the issue. This is one thing that keeps us from publishing an official macOS version right now.

@schneisi If you have the time, could you have a look? I presume that the PLIST file for macOS needs improvements.

**Comment by kebekus** [comment]
The problem should be fixed in the current developer version.

@mipastgt Thank you for the report!
