### ISSUE TITLE
Maximum zoom level is too small for airport/taxi charts

### ISSUE THREAD

**Issue by mipastgt** [Akaflieg-Freiburg/enroute#393]
I have just added (not yet released) support for airport/taxi charts in **AIP Browser DE** but I noticed that the maximum zoom level is too small to make these charts usefull in Enroute.
<img width="1092" alt="Bildschirmfoto 2024-03-20 um 19 36 18" src="https://github.com/Akaflieg-Freiburg/enroute/assets/16735714/b855e495-210c-4323-8e12-5d45413e2566">
Image showing maximum zoom level.

It would be nice if this maximum zoom level could be increased, so that you can actually see where you are on an airport and where you can read the important information like taxiway names etc.

I have added a geo-referenced, pre-transformed chart image as a reference.
[EDDS_Stuttgart 5-geo.tiff.zip](https://github.com/Akaflieg-Freiburg/enroute/files/14695537/EDDS_Stuttgart.5-geo.tiff.zip)
(It's a zipped tiff because GitHub doesn't allow direct tiff uploads.)

**Comment by kebekus** [comment]
Roger. The feature will be implemented; details are pending.

**Comment by kebekus** [comment]
Fixed in 2.30.12, which will appear for Android today. An iOS version will appear in a while.
