### ISSUE TITLE
Possibility to temporarily hide a VAC

### ISSUE THREAD

**Issue by mipastgt** [Akaflieg-Freiburg/enroute#394]
**Is your feature request related to a problem? Please describe.**
There is currently no way to determine whether a VAC is correctly geo-referenced and shown on the map. It also may just hide some important information you are interested in.

**Describe the solution you'd like**
I'd like to have the possibility to temporarily hide the VAC, e.g. via a button in the top-right corner of the screen, without otherwise changing the map display. See example:
<img width="817" alt="Bildschirmfoto 2024-03-24 um 13 44 22" src="https://github.com/Akaflieg-Freiburg/enroute/assets/16735714/50c185d8-f403-47f7-9d36-290bd2440d81">
I'd like the VAC image to be replaced by a light grey rectangle outline of the VAC corner points.

**Comment by kebekus** [comment]
I understand the issue, but the feature seems out of scope for an app that concentrates on supporting the pilot in flight. I ask for your understanding!
