### ISSUE TITLE
Jump to the center of the corner points of a selected VAC

### ISSUE THREAD

**Issue by mipastgt** [Akaflieg-Freiburg/enroute#395]
**Is your feature request related to a problem? Please describe.**
When you are not flying (most relevant for the desktop varinants of Enroute) and you select a VAC, the map always jumps to Freiburg, independently of the selected VAC. You then have to manually move the map to the chosen chart area.

**Describe the solution you'd like**
In case you are not flying and thus don't have a current position, the map should just jump to the center of the corner points of a selected VAC. That would save a lot of manual shifting and zooming.

**Comment by kebekus** [comment]
The latest version fixes the problem, though not quite in the way you suggested. The map does not move at all when VACs are (de)selected.
