### ISSUE TITLE
Mode "North Up" unstable on pinch gesture

### ISSUE THREAD

**Issue by kebekus** [Akaflieg-Freiburg/enroute#405]
One user complained that the mode "North Up" is quickly lost on pinch gestures.

**Comment by tue-kyndal** [comment]
I agree... The map should not be allowed to rotate at all when in north mode.. On zoom/pinch. Just zooming and move. 

Currently its all over the place... Especially if there is a bit of turbulence.

This just adds stress and confusion.

**Comment by kebekus** [comment]
Roger. It will take a while until I have time to look at this.

**Comment by kebekus** [comment]
@tue-kyndal This is fixed; the fix will appear with the next release. There is a threshold now; you need to rotate by more than 20° before rotation has any effect. That should hopefully resolve all practical problems.
