### ISSUE TITLE
Weather/Notam connection issue

### ISSUE THREAD

**Issue by KenjiWi** [Akaflieg-Freiburg/enroute#422]
While trying to request Weather/Notam information the following connection error appears on iOS/iPadOS devices. It does not appear on Android device

![IMG_1425](https://github.com/user-attachments/assets/a502eeef-939c-487d-b8bf-341ad78735a9)

 - OS: iOS/iPadOS 17.5.1 (iPhone XS/ iPad Air 5)
 - App Version 2.30.19
.

**Comment by 5630Klaus** [comment]
Have the same problem. Unable to download weather and metar information. iPad 8th gen. iOS 17.5.1

**Comment by kebekus** [comment]
Thank you for your report. The issue should be fixed now. Can you please check? If the issue persists, then please re-open this report!

**Comment by 5630Klaus** [comment]
Problem solved. Thank you!
