### ISSUE TITLE
Support additional TripKit formats

### ISSUE THREAD

**Issue by kebekus** [Akaflieg-Freiburg/enroute#425]
Michael Paus requests that Enroute supports TripKits where the files do live in the main directory of the ZIP, but in a first-level subdirectory.

**Comment by kebekus** [comment]
Implementiert, wird mit der nächsten App-Version erscheinen. Ich melde mich dann noch einmal.

**Comment by mipastgt** [comment]
Danke. Ich werde das dann aber erst nach einer Übergangszeit nutzen bis (hoffentlich) alle Nutzer auch die neue Version installiert haben.

**Comment by kebekus** [comment]
Closing because implemented.
