### ISSUE TITLE
transparent setting for bearingless airplanes

### ISSUE THREAD

**Issue by OdomLinx** [Akaflieg-Freiburg/enroute#427]
**Is your feature request related to a problem? Please describe.**
In some airspaces, e.g. RMZ, the map displays are sometimes difficult to recognize for some people in bearingless aircraft

**Describe the solution you'd like**
in file src/qml/items/MFM.qml line 296 change from:
 opacity: 0.3
to:
 opacity: 0.1

**Describe alternatives you've considered**
Possibly also adjustable via the menu

**Additional context**
here screenshots for comparison
bearingless traffic opacity =0.3
![Traffic_opacity_0_3](https://github.com/user-attachments/assets/3aeed7f9-71a1-4002-8c18-c038f070cae3)

bearingless traffic opacity =0.1
![Traffic_opacity_0_1](https://github.com/user-attachments/assets/a9fb5944-7fd5-49ad-823b-32548a5f60fe)

bearingless traffic with alert opacity =0.3
![Trafficalert_opacity_0_3](https://github.com/user-attachments/assets/dc05b134-e93b-4cdc-9fad-827ffd69209f)

bearingless traffic with alert opacity =0.1
![Trafficalert_opacity_0_1](https://github.com/user-attachments/assets/84dc5c67-3bdd-4025-bc53-ed7f905941eb)

**Comment by kebekus** [comment]
Thank you for the suggestion. We will definitively consider that, but we will need a few days. At the moment our ressources are used 100% by enlarging the infrastructure, to make NOTAMs work reliably again. We will come back to you as soon as we can find the time.

**Comment by kebekus** [comment]
@OdomLinx Do you want to join the development? We are definitively looking for help!

**Comment by OdomLinx** [comment]
> @OdomLinx Do you want to join the development? We are definitively looking for help!

I'm not the best programmer, I never really got beyond "C++ in 21 days". It's enough to customize a few lines.

**Comment by kebekus** [comment]
Implemented. The fix will be contained in the next release.

@OdomLinx Thank you for your help! Please keep reporting issues and suggestions for enhancement. Feel free to submit pull requests.
