### ISSUE TITLE
No VACs visible on map since App update

### ISSUE THREAD

**Issue by Maurer-1** [Akaflieg-Freiburg/enroute#431]
Since I have updated the App on IOS to version 2.31.8 first all of my formerly saved VACs disappeared, the library was empty.
So I started to re-import my existing VACs (as geo-tiffs) and they appear again in the library, but when I choose them in the menu none of them appears on the map.
Can you please check and if possible fix that issue?

Thanks
Stefan

**Comment by kebekus** [comment]
@Maurer-1 Ouch! This should not happen!

@schneisi Simon, kannst Du bitte einmal schauen, was da los ist? Kannst Du den Fehler reproduzieren?

**Comment by kebekus** [comment]
@Maurer-1 Thank you for the report. We will look at the issue ASAP.

**Comment by schneisi** [comment]
I can reproduce the issue

**Comment by schneisi** [comment]
The appearance on the map will be fixed with the next release.

I could also reproduce the empty library after an app update, but it takes a little longer to dig into this.

**Comment by Maurer-1** [comment]
Great.. thx for the quick problem solution. It is not so much effort to import the VACs again, as long as they appear on the map again.

thanks again

stefan

**Comment by Maurer-1** [comment]
With the new IOS App Version 2.31.9 the visibility of the VACs on the map works again.
Great Job... thanks !!!!

**Comment by kebekus** [comment]
@Maurer-1 Good to hear that the problem has been resolved. I am closing this issue now. Feel free to open more issue reports if you find any problems!

@schneisi Thank you for the quick reaction.
