### ISSUE TITLE
Current macOS developer build does not show any window when launched

### ISSUE THREAD

**Issue by mipastgt** [Akaflieg-Freiburg/enroute#436]
**Describe the bug**
The current macOS developer build does not show any window when launched. The application gets started and keeps running but does not show any window. An older version, which I downloaded on 3. June, works as always. 

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.6.1

**Comment by kebekus** [comment]
Ich kann das Problem auf meinem Rechner nachvollziehen.

**Comment by kebekus** [comment]
@mipastgt The problem should be fixed now. Can you please check? -- Thanks!

**Comment by mipastgt** [comment]
@kebekus I can confirm that the latest version works again as before. Thanks.

**Comment by kebekus** [comment]
@mipastgt Danke, noch einmal, für den Hinweis!
