### ISSUE TITLE
Failure: GitHub actions for Android and iOS

### ISSUE THREAD

**Issue by kebekus** [Akaflieg-Freiburg/enroute#437]
Actions need to be fixed to work again.

**Comment by TTC70** [comment]
Hey Stefan.
Could you please say what is this issue?

**Comment by kebekus** [comment]
GitHub actions for building Android and iOS binaries fail like this: https://github.com/Akaflieg-Freiburg/enroute/actions/runs/10805213689

**Comment by kebekus** [comment]
The action for iOS seems to be working again, but the action for Android still fails.

**Comment by TTC70** [comment]
I confirm that on my Samsung Galaxy S10 with Android 12, everything works
properly.
Antonio

Il Mer 18 Set 2024, 07:30 Stefan Kebekus ***@***.***> ha
scritto:

**Comment by kebekus** [comment]
@TTC70 Misunderstanding: The GitHub action provides test-builds for the development versions of the app. This has nothing to do at all with the program version that you have on your phone.

**Comment by kebekus** [comment]
Fixed.
