### ISSUE TITLE
Compiling on Raspberry Pi 4

### ISSUE THREAD

**Issue by ocean71** [Akaflieg-Freiburg/enroute#475]
I have a Raspberry Pi 4 and am trying to compile Enroute following these instructions:

# In source directory
git submodule init
git submodule update

# Create build directory
mkdir build
cd build

# Configure
cmake ..

# Build
make -j5

# Enjoy

However, I hit a problem at the 'git submodule update' stage.  The git repositories are cloned as expected one by one until I come to material-design-icons.
When it reaches this point it appears to hang, but in fact it is downloading a very large
amount of data (several gigabytes). I allowed it to continue for a while, but then
stopped it as the folder was getting big. 

Is this supposed to be a large module, or am I doing something wrong? I downloaded enroute using the usual git clone command. 
Thanks for your help.

**Comment by kebekus** [comment]
@ocean71 Thanks for your report. Enroute Flight Navigation is a complex build and relies on many submodules. It also relies on MapLibreQt, which needs to be compiled separately before Enroute can even be configured.

At the moment, the Git Repository of Enroute pulls in material-design-icons as a submodule. This submodule is absurdly huge, about 4 GB, in fact. There is currently no avoiding this. We do have one suggestion to move over to fontawesome icons,

- https://github.com/Akaflieg-Freiburg/enroute/issues/415

which could solve the problem, but so far no-one has volunteered to do the work. It seems that I have no good solution to you problem. I am sorry that I have no better news.
