### ISSUE TITLE
Option. Choosing your own AirCraft Icon

### ISSUE THREAD

**Issue by TTC70** [Akaflieg-Freiburg/enroute#478]
**Is your feature request related to a problem? Please describe.**
Replacement for the rounded blue circle.

**Describe the solution you'd like**
The menu aircraft configuration menu could show a drop down menu where the pilot could choose the icon and color for his/her aircraft. 

**Describe alternatives you've considered**
Non alternatives.
Though, the access to the same menù could be from tapping the icon of the aircraft from the moving map.

**Additional context**
These are the icons used by SafeSky (with which Enroute is compatible - please let me know if you want the aircrafts splitted in 12 single items):
![Aircrafts](https://github.com/user-attachments/assets/dfbab3c9-d944-4922-855a-8be304cd4a37)

**Comment by kebekus** [comment]
@TTC70 Thanks! We considered your suggestion, but eventually decided against implementing the feature. Reson: The main selling point of Enroute Flight Navigation is its simplicity. Striving to keep the app as simple as possible, we try hard to keep the number of options at the absolute minimum, even if that means that we do not implement all nice-to-have features.

We know that this is not the answer you were hoping for, and ask for your understanding.
