### ISSUE TITLE
Add route button underneath the menu button in top left of map view.

### ISSUE THREAD

**Issue by HeinerTholen** [Akaflieg-Freiburg/enroute#53]
Okay, so this might be a little controversial. 

I'm using the routing functionality more than anything else and I feel that it is too far away at two taps. I would love to have it at one tap, with a shortcut button right under the menu button in the upper left corner of the map view.

Happy to discuss!

**Comment by kebekus** [comment]
Dear Heiner,

I am not sure that this suggestion would improve the app experience for most user … as you say, the matter is a little controversial. I would therefore rather leave the app 'as is' and move to other projects.

Best,

Stefan.
