### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by ninelima** [Akaflieg-Freiburg/enroute#72]
Haptic feedback cannot be disabled.  

It should use the system settings; or there should be an option in settings to enable/disable.

**Comment by kebekus** [comment]
Dear Ninelima,

I thought about your suggestion, but then decided against it. In my experience, users like the hapic feeback (in particular during flight), and aiming to keep the app as simple as possible, I am very hesitant to add new options to the GUI. I would therefore rather leave the app as is.

Best wishes,

Stefan.
