### ISSUE TITLE
lack of contrast on maps

### ISSUE THREAD

**Issue by andre-ada** [Akaflieg-Freiburg/enroute#78]
Hi,
Allow me a small remark concerning the aeronautical chart.

In my opinion, it lacks contrast, particularly for small woods (some not to be seen on the map) and forests.

I attach a screenshot for Belgium, of the surroundings of my EBNM airfield (Namur), taken from my Samsung 7 " tablet, with 4 stars (*) indicating the absence of small woods, to compare with a screenshot from the ICAO chart taken from your site, where these woods (and others) are present.

In flight, with strong light, all the elements suitable for finding one's way are of great importance.

I hope you will be able, as you are with other aspects of the program, to give it the necessary attention.

Thank you and wish you a big success with Enroute.

André Darquennes

Belgium

![Enroute_map2](https://user-images.githubusercontent.com/70091892/90974840-43169b00-e52f-11ea-84da-b49cb1196a7d.png)
![Enroute_map1](https://user-images.githubusercontent.com/70091892/90974844-490c7c00-e52f-11ea-89a8-7bb1a0b084e1.png)

**Comment by kebekus** [comment]
Dear André,

thank again for your report. I have increased the map contrast in version 2.3.0, which is scheduled to appear in mid-February.

Best,

Stefan.

**Comment by andre-ada** [comment]
Good afternoon, Stefan.
Thanks  a lot for the improvement of the map. I'll appreciate.
One short remark regarding the French translation.
Would you please ask Adrien to modify the word "Autheurs" which must be
"Auteurs" (without h).
Congratulations for Enroute.
Best regards.
André


Le dim. 17 janv. 2021 à 12:56, Stefan Kebekus <notifications@github.com> a
écrit :

**Comment by acrovato** [comment]
Hi André,

Thanks for your feedback, I'll make the change next week. If you notice any other mistranslations, you can mention me using @acrovato. I usually read all the reports, but in case I miss one...

See you in Namur!

**Comment by acrovato** [comment]
Bonjour André,

Oui, je suis également pilote à Namur depuis environ un an. A mon avis, on ne s'est pas encore croisé vu les mesures sanitaires...

Merci pour les corrections ! Maintenant que j'y repense, c'est peut être mieux de m'envoyer les suivantes par e-mail (a.crovato@uliege.be) pour ne pas que tous les membres du projet soient notifiés inutilement. ;-)

En ce qui concerne ta question sur l'impression du FPL, je ne suis pas certain que ça fasse partie des priorités, car Stefan voit l'application comme étant un outil de suivi de vol plutôt qu'un outil de préparation. J'avais créé des fiches de calcul excel pour faire les calculs pre-flight. N'hésite pas à m'envoyer un mail si ça t'intéresse !
