### ISSUE TITLE
Show Reach of Glide Path

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enroute#80]
Show Reach of Glide Path

Precondition: Elevation data available

Feature:

User enters the glide ratio of his aircraft. Enroute draws a circle around the current position showing what area can be reached in case of engine failure (or without engine on board).

Modes: on/off/auto (auto means: auto-ON above a reasonable altitude AGL, e.g. 500 ft, auto-OFF below this altitude).

Variant:

Draw semicircle: from 9 o'clock to 3 o'clock (heading is 12 o'clock); in other words: from heading minus 90° to heading plus 90° (in some cases: + 360 or MOD 360).

Simplification (if a circle is difficult to implement):  

The 5-minute-beam shows in different colors both pieces of information. The pilot estimates the reach in other directions.

Advanced feature:

User enters wind data for his flight altidute. The calculation of the circle/beam takes these wind data into account.

Extended edition: Wind data come automatically from external sources like aviation weather, windy.com etc.

Hint:

User should know that GPS altitude often is inaccurate close to ground. Manual should recommend auto-mode as default.

**Comment by kebekus** [comment]
Hi, as you write yourself: this feature requires elevation data, which we do not have. Flying in the Black Forest, I know from exerience that it required PRECISE elevation data in regions where mountains are steep.

I cannot see that we implement this feature in the reasonably near future and will therefore close the issue now. I ask for your understanding.
