### ISSUE TITLE
Using own JPG/PNG files as traffic circuit

### ISSUE THREAD

**Issue by lucabert** [Akaflieg-Freiburg/enroute#84]
Since OpenAIP does not have the traffic circuit for many little airfield, it could be a nice idea to upload the circuit as image (JPG/PNG/GIF/whatever) in some format to geolocalize.
Other Apps have this option.

**Comment by kebekus** [comment]
This is possible, but complicated to implement. Unless someone speaks up and is willing to implement it, I would rather do other things first. I will therefore close this issue and ask for your understanding that ressources are limited.
